language: cpp
dist: trusty
#sudo: false
cache:
  directories:
  - $HOME/.cache/pip


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
      - deadsnakes
    packages:
      - g++-multilib
      - libhdf5-serial-dev
      #- python3.5
      #- python3.5-dev
      #- python3.5-venv
      #- python3.5-dev:i386
      - libboost-thread1.55-dev
      - libboost-system1.55-dev
      - libboost-date-time1.55-dev
      - libboost-chrono1.55-dev
      - libboost-python1.55-dev
      - python-numpy
      - python-pip
      - python-nose 


before_install:
      - if [ `uname` = "Darwin" ]; then
           brew update >/dev/null;
           brew install homebrew/science/hdf5;
        fi


matrix:
  include:
    - os: linux
      compiler: gcc
      script:
          - cmake . -DWITH_BOOST=TRUE -DWITH_HDF5=TRUE -DWITH_AD3=FALSE -DWITH_TRWS=FALSE  -DWITH_QPBO=FALSE -DWITH_MRF=FALSE  -DWITH_GCO=FALSE  -DWITH_CONICBUNDLE=FALSE  -DWITH_MAXFLOW=FALSE  -DWITH_MAXFLOW_IBFS=FALSE -DBUILD_PYTHON_WRAPPER=TRUE -DBUILD_COMMANDLINE=FALSE -DCI=TRUE
          #- make  externalLibs -j4
          - cmake . -DWITH_BOOST=TRUE -DWITH_HDF5=TRUE -DWITH_AD3=FALSE -DWITH_TRWS=FALSE  -DWITH_QPBO=FALSE -DWITH_MRF=FALSE  -DWITH_GCO=FALSE  -DWITH_CONICBUNDLE=FALSE  -DWITH_MAXFLOW=FALSE  -DWITH_MAXFLOW_IBFS=FALSE -DBUILD_PYTHON_WRAPPER=TRUE -DBUILD_COMMANDLINE=FALSE -DCI=TRUE
          - make -j4
          - make test ARGS="-V"
          #- make test-python-wrapper
          - sudo make install
          #
    - os: osx
      compiler: clang
      script:
          - cmake . -DWITH_BOOST=TRUE -DWITH_HDF5=TRUE -DWITH_AD3=FALSE -DWITH_TRWS=FALSE  -DWITH_QPBO=FALSE -DWITH_MRF=FALSE  -DWITH_GCO=FALSE  -DWITH_CONICBUNDLE=FALSE  -DWITH_MAXFLOW=FALSE  -DWITH_MAXFLOW_IBFS=FALSE -DBUILD_PYTHON_WRAPPER=FALSE -DBUILD_COMMANDLINE=FALSE -DCI=TRUE
          #- make  externalLibs -j4
          - cmake . -DWITH_BOOST=TRUE -DWITH_HDF5=TRUE -DWITH_AD3=FALSE -DWITH_TRWS=FALSE  -DWITH_QPBO=FALSE -DWITH_MRF=FALSE  -DWITH_GCO=FALSE  -DWITH_CONICBUNDLE=FALSE  -DWITH_MAXFLOW=FALSE  -DWITH_MAXFLOW_IBFS=FALSE -DBUILD_PYTHON_WRAPPER=FALSE -DBUILD_COMMANDLINE=FALSE -DCI=TRUE
          - make -j4
          - make test ARGS="-V"
          #- make test-python-wrapper
          - sudo make install

